### ISSUE TITLE
How to pass in service principle client/secret?

### ISSUE THREAD

**Issue by nathangiusti** [TabularEditor/DevOps#1]
We authenticate via Azure Active Directory. We have a service principle whose credentials we would like to use. 

Currently I am running

'TabularEditor.exe .\\Nathan_TE_Test -D powerbi://api.powerbi.com/v1.0/myorg/Alchemy%20Datasets%20%5BTest%5D Nathan_TE_Test -O -C -G -E -W'

This causes the dataset to be deployed correctly but requires me to login to my account. How do we pass in service principle credentials for use?

**Comment by otykier** [comment]
Hi Nathan,

Specify the full connection string after the -D parameter, like this:

```cmd
TabularEditor.exe .\Nathan_TE_Test -D "Provider=MSOLAP;Data Source=powerbi://api.powerbi.com/v1.0/myorg/Alchemy%20Datasets%20%5BTest%5D;User ID=app:<application-id>@<tenant-id>;Password=<app-secret>" Nathan_TE_Test -O -C -G -E -W
```

See [here](https://docs.tabulareditor.com/te2/Command-line-Options.html#connecting-to-azure-analysis-services) for more information (same connection string syntax applies to Azure Analysis Services and Power BI XMLA).
